stories=[
{title:"Moon: Origin and Evolution",
 content:"The Apollo and Luna missions brought Moon rocks to Earth that have given us a better understanding of the origin of the Moon. By analysing these rocks, we can study the evolution of not only the Moon but the entire Earth-Moon system. The Moon probably formed after the collision of a Mars-sized object with the Earth. The interior of the Moon is similar to that of the Earth, with a crust, a mantle and a core. As we seek to better understand the Moon’s complex morphology, we realise it could be an important resource for space exploration. But before we can use it as a resource, we need to understand how the Moon came to be and what we can find on our natural satellite.",
	imgurl:"apollo_11_swc.jpg"},
{title:"Earth-Moon System",
 content:"Earth and our Moon are unique in the Solar System. Earth is the only rocky planet that has a large natural satellite. Other planets in the Solar System have large moons, some even larger than ours, but no other planet in the Solar System has such a relatively large moon.The Moon has very noticeable effects on Earth, such as tides, which are caused by the Moon\'s gravity. When the Moon first formed, it was much closer to Earth, and appeared at least 10 times larger in the sky. The tidal effects were much stronger than they are today and may have had important geological effects, such as keeping Earth’s magma hot and creating additional convection in Earth’s mantle. After Earth started to cool, the first crust started to float on top of magma, shaping Earth as we know it today. This may have led to Earth\'s plate tectonics that are unique among the rocky planets. During this period, Earth was also subjected to increased meteor bombardment, which may have brought about the origins of life. Many of the large basins on the Moon are evidence of this late heavy bombardment period. In this respect, the Moon is a history book for the inner Solar System and Earth.We have to understand the effects of the Moon on Earth to get an insight on the origins of life and whether this is a unique feature of our planetary system.",
 imgurl:"New_High-Resolution_Earthrise_Image.jpg"},
{title:"Lunar Resources",
content:"Working on the Moon or in space requires resources such as power, fuel and materials. We can load all we need onto a rocket, but this is inefficient and expensive, so using lunar resources is an enticing option for mission designers.We know water can be found in permanently shadowed areas towards the Moon\'s poles and some areas are constantly illuminated. Because there are no clouds and no atmosphere, they offer an ideal place to generate electricity from solar power. The Moon also contains metals such as iron, titanium and uranium. Making rocket fuel with the resources on the Moon would make it viable to refuel spacecraft in the lunar vicinity. By exploring the Moon in more detail we will know if any resources could be economically valuable to export to Earth.",
 imgurl:"1024px-LADEE_in_moon_orbit.jpg"}
]
